### ISSUE TITLE
一直在in thread...中

### ISSUE THREAD

**Issue by qieqiuyue** [Frrrrrrrrank/auto_job__find__chatgpt__rpa#10]
![image](https://github.com/Frrrrrrrrank/auto_job__find__chatgpt__rpa/assets/56438921/84fa6ee3-3cf5-43fa-a428-93ad7e9bf96d)
用得是gpt3.5，在openai api的assistants也有对应的assistant_id，已经开了代理，pdf只有1页，但在in thread...步骤中停止了

**Comment by Frrrrrrrrank** [comment]
啊这...如果一直不报错误的话，那意味着代码应该问题不大，只是由于网络连接很慢导致的。。。如果你能抓到错误信息的话或许能够有办法分析原因，但这我实在也不知道为啥...要不多等等？如果最终输出成功的话，那应该就是网络问题

**Comment by qieqiuyue** [comment]
> 啊这...如果一直不报错误的话，那意味着代码应该问题不大，只是由于网络连接很慢导致的。。。如果你能抓到错误信息的话或许能够有办法分析原因，但这我实在也不知道为啥...要不多等等？如果最终输出成功的话，那应该就是网络问题

解决了，只是没额度了而已

**Comment by Frrrrrrrrank** [comment]
那就行
