### ISSUE TITLE
作者您好，基于您的项目，我做了一个NodeJs版本的，这样对前端开发者更加友好，并且免费

### ISSUE THREAD

**Issue by noBaldAaa** [Frrrrrrrrank/auto_job__find__chatgpt__rpa#12]
这是地址链接：https://github.com/noBaldAaa/find-job

并始终附上了您的视频地址和项目地址，您介意吗？

您介意的话我将会删除，希望得到您的回复和建议，谢谢。

**Comment by Frrrrrrrrank** [comment]
感谢您的贡献，我会将您项目的链接同时加入我的readme中

**Comment by Frrrrrrrrank** [comment]
此问题结束
