### ISSUE TITLE
成功登陆后报错（Win11，下拉框工作标签识别失败）

### ISSUE THREAD

**Issue by Bolun001** [Frrrrrrrrank/auto_job__find__chatgpt__rpa#13]
Win11 12H2
谷歌最新的浏览器
python版本3.10.8 64位

已经配置了boss的职位下拉菜单，write_response.py 文件中也设定了同样的名字

master/auto_job_find/write_response.py
OpenAI version is compatible.
Loaded existing assistant ID.
Loaded existing assistant ID.

DevTools listening on ws://127.0.0.1:43203/devtools/browser/8b50061a-1638-4583-beb5-7c086dd7bd14
Received message: 《职位描述》：
【经验要求】：此处省略
【语言要求】：此处省略
【岗位职责】：
此处省略

【岗位要求】：
1）本科学历及以上优先，2023及2024届德法西意小语种优秀毕业生；
2）工作积极主动，具有较强的学习能力、数据分析能力及创新能力。

【福利待遇】：
此处省略！
我们是深耕智能穿戴——手表类10年，亚马逊运营团队30人及以上，主攻市场为欧美、北美、日本等，未来全站点全产线布局，期待您的加入 ！！！ in thread thread_hfInLbNv3cl1yQdzs37iXZ06
An error occurred: Error code: 404 - {'error': {'message': "No assistant found with id 'asst_PWWazfRU4PZEiNVnqOxU2sEx'.", 'type': 'invalid_request_error', 'param': None, 'code': None}}
{"error": "Error code: 404 - {'error': {'message': \"No assistant found with id 'asst_PWWazfRU4PZEiNVnqOxU2sEx'.\", 'type': 'invalid_request_error', 'param': None, 'code': None}}"}
An error occurred: Message: stale element reference: stale element not found
  (Session info: chrome=120.0.6099.200); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
        GetHandleVerifier [0x00007FF68A842142+3514994]
        (No symbol) [0x00007FF68A460CE2]
        (No symbol) [0x00007FF68A3076AA]
        (No symbol) [0x00007FF68A30CFC0]
        (No symbol) [0x00007FF68A30F38F]
        (No symbol) [0x00007FF68A30F480]
        (No symbol) [0x00007FF68A3587E5]
        (No symbol) [0x00007FF68A3568ED]
        (No symbol) [0x00007FF68A3540EC]
        (No symbol) [0x00007FF68A352EA5]
        (No symbol) [0x00007FF68A346A0F]
        (No symbol) [0x00007FF68A375FEA]
        (No symbol) [0x00007FF68A3463B6]
        (No symbol) [0x00007FF68A376490]
        (No symbol) [0x00007FF68A3928F6]
        (No symbol) [0x00007FF68A375D93]
        (No symbol) [0x00007FF68A344BDC]
        (No symbol) [0x00007FF68A345C64]
        GetHandleVerifier [0x00007FF68A86E16B+3695259]
        GetHandleVerifier [0x00007FF68A8C6737+4057191]
        GetHandleVerifier [0x00007FF68A8BE4E3+4023827]
        GetHandleVerifier [0x00007FF68A5904F9+689705]
        (No symbol) [0x00007FF68A46C048]
        (No symbol) [0x00007FF68A468044]
        (No symbol) [0x00007FF68A4681C9]
        (No symbol) [0x00007FF68A4588C4]
        BaseThreadInitThunk [0x00007FFFD8A1257D+29]
        RtlUserThreadStart [0x00007FFFDA38AA58+40]
工作标签修改之后，可以正常点击到对应的工作标签类型（数据工程师（深圳）），然后弹出薪资选项之后程序报错。
在发消息的时候，发出的是一串乱码。

**Comment by Bolun001** [comment]
在上述错误中，察觉到识别下拉标签失败后，将该部分的XPath改为了//*[@id='wrap']/div[2]/div[1]/div/div[1]/div[1]，只选择一项标签，成功进入了下一步发消息，不过后续依旧报错，求助

**Comment by Frrrrrrrrank** [comment]
下拉标签失败，是不是也是因为你的账号是三个并列标签？我下周得空，搞个你们这样的账号来修改一下我的相关函数pull一下。

不过你提到你将xpath改好了，进入了发消息，这时候报错是什么错误？能否将错误消息贴一下

**Comment by Frrrrrrrrank** [comment]
最新代码中，下拉框问题已修复
