### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by WINTERYARK** [Frrrrrrrrank/auto_job__find__chatgpt__rpa#18]
我在把OPENAI_API_KEY自己的OPENAI_BASE_URL配置好后运行write_responds.py文件的时候出现了以下报错：

OpenAI version is compatible.
Traceback (most recent call last):
  File "D:\auto_job__find__chatgpt__rpa-master\auto_job_find\write_response.py", line 36, in <module>
    assistant_id = functions.create_assistant(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\auto_job__find__chatgpt__rpa-master\auto_job_find\functions.py", line 41, in create_assistant
    file_ids=[file.id])
              ^^^^^^^
AttributeError: 'str' object has no attribute 'id'

进程已结束,退出代码1

我的python版本是3.11，请问该怎么解决这个问题，感谢

**Comment by Frrrrrrrrank** [comment]
似乎是因为没有找到对应的文件，请问您的my_cover.pdf放在了哪里？如果在在resume中，则尝试和write_response放在同一个文件夹

**Comment by WINTERYARK** [comment]
> 似乎是因为没有找到对应的文件，请问您的my_cover.pdf放在了哪里？如果在在resume中，则尝试和write_response放在同一个文件夹

![屏幕截图 2024-01-08 230438](https://github.com/Frrrrrrrrank/auto_job__find__chatgpt__rpa/assets/102876303/0f89f01c-6b7c-450d-8895-231d3e506578)

我把my_cover.pdf放在了和write_response同一个文件夹，但是还是同样的报错

**Comment by Frrrrrrrrank** [comment]
我明白了，你是不是用的非openai的官方api，然后需要自己填url那种？如果是的话，你问问卖你的老板，支持不支持assisttant创建和文件上传
