### ISSUE TITLE
运行后扫码登录成功后报错

### ISSUE THREAD

**Issue by Kwaiyu** [Frrrrrrrrank/auto_job__find__chatgpt__rpa#19]
OpenAI version is compatible.
An error occurred: Error code: 400 - {'error': {'message': "3.0 is greater than the maximum of 2 - 'temperature'", 'type': 'invalid_request_error', 'param': None, 'code': None}}

进程已结束,退出代码0

ENV：
Python 3.10.10
win10

OPENAI_BASE_URL=https://api.openai.com/v1
OPENAI_API_KEY='sess-EkhvXXXXXXXXXXXX'

修改后：
`    llm = ChatOpenAI(temperature=2, openai_api_base=OPENAI_BASE_URL, openai_api_key=OPENAI_API_KEY)
`
重新运行扫码登录后报错：
An error occurred: Error code: 400 - {'error': {'message': "This model's maximum context length is 4097 tokens. However, your messages resulted in 5600 tokens. Please reduce the length of the messages.", 'type': 'invalid_request_error', 'param': 'messages', 'code': 'context_length_exceeded'}}

进程已结束,退出代码0

**Comment by Frrrrrrrrank** [comment]
您所使用的是langchain版本是吗？
如果您的简历内容过多，可以尝试修改以下代码:
```
def get_text_chunks(text):
    text_splitter = CharacterTextSplitter(
        separator="\n",
        chunk_size=2000,
        chunk_overlap=200,
        length_function=len
    )
    chunks = text_splitter.split_text(text)
```
将chunk_size的值调小，比如500，chunk_overlap在我看来保持在20-50即可

**Comment by Kwaiyu** [comment]
> 您所使用的是langchain版本是吗？ 如果您的简历内容过多，可以尝试修改以下代码:
> 
> ```
> def get_text_chunks(text):
>     text_splitter = CharacterTextSplitter(
>         separator="\n",
>         chunk_size=2000,
>         chunk_overlap=200,
>         length_function=len
>     )
>     chunks = text_splitter.split_text(text)
> ```
> 
> 将chunk_size的值调小，比如500，chunk_overlap在我看来保持在20-50即可

OK，感谢大佬！用langchain版本这个方法有效，但遇到了新的问题，投了两个岗位后停止运行，输出一堆HTML。

改用assistant方式运行，扫码登录后一直卡在登录后网页不动，控制台只输出了OpenAI version is compatible.

**Comment by Frrrrrrrrank** [comment]
langchain版本我没有深度测试过，你说的问题我没遇到过，你可以把输出的内容给我看看我排查一下

如果控制台只输出了OpenAI version is compatible，那么应该是网络的问题，这时候应该是在创建assistant，如果你没看到assisatant_id.json的话，那就是没有创建代理成功，只能多等一会了...或者优化一下网络
