### ISSUE TITLE
需要使用的faiss-cpu包，尚不支持3.12，需要degrade到3.11及以下版本

### ISSUE THREAD

**Issue by huanmit** [Frrrrrrrrank/auto_job__find__chatgpt__rpa#27]
跑write_response的时候发现还有几个requirements里面没有涵盖的包，faiss-cpu不支持3.12（faiss-gpu不清楚）。建议作者在readme中提示大家用3.11及以下版本的python运行脚本。

**Comment by Frrrrrrrrank** [comment]
感谢您的信息！
