### ISSUE TITLE
pwd包报错

### ISSUE THREAD

**Issue by loks666** [Frrrrrrrrank/auto_job__find__chatgpt__rpa#37]
已连接到 pydev 调试器(内部版本号 233.13763.11)Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "H:\Project\AI\auto_job__find__chatgpt__rpa\auto_job_find\langchain_functions.py", line 1, in <module>
    from langchain.document_loaders import DirectoryLoader, PyPDFLoader
  File "H:\anaconda3\lib\site-packages\langchain\document_loaders\__init__.py", line 18, in <module>
    from langchain_community.document_loaders.acreom import AcreomLoader
  File "H:\anaconda3\lib\site-packages\langchain_community\document_loaders\__init__.py", line 163, in <module>
    from langchain_community.document_loaders.pebblo import PebbloSafeLoader
  File "H:\anaconda3\lib\site-packages\langchain_community\document_loaders\pebblo.py", line 5, in <module>
    import pwd
ModuleNotFoundError: No module named 'pwd'

这个代码中使用了 langchain 这个库，而且根据你之前提供的错误日志，该库中有一些模块尝试导入 pwd，这是一个 Unix-specific 的模块，不在 Windows 系统中可用。因此，如果这些模块是必需的，那么这个代码可能无法在 Windows 上运行。

说实话大佬你这代码不支持windows有点太狗血了哦

**Comment by Frrrrrrrrank** [comment]
不应该呀，我的就是windows...你试一下不用langchain的版本

**Comment by digger-yu** [comment]
i have same issue

```
PS D:\git\auto_job__find__chatgpt__rpa\auto_job_find> & d:/git/auto_job__find__chatgpt__rpa/auto_job_find/.venv/Scripts/python.exe d:/git/auto_job__find__chatgpt__rpa/auto_job_find/write_response.py
Traceback (most recent call last):
  File "d:/git/auto_job__find__chatgpt__rpa/auto_job_find/write_response.py", line 11, in <module>
    from langchain_functions import get_text_chunks, get_vectorstore, read_resumes, should_use_langchain, generate_letter
  File "d:\git\auto_job__find__chatgpt__rpa\auto_job_find\langchain_functions.py", line 1, in <module>
    from langchain.document_loaders import DirectoryLoader, PyPDFLoader
  File "D:\git\auto_job__find__chatgpt__rpa\auto_job_find\.venv\lib\site-packages\langchain\document_loaders\__init__.py", line 18, in <module>
    from langchain_community.document_loaders.acreom import AcreomLoader
  File "D:\git\auto_job__find__chatgpt__rpa\auto_job_find\.venv\lib\site-packages\langchain_community\document_loaders\__init__.py", line 163, in <module>
    from langchain_community.document_loaders.pebblo import PebbloSafeLoader
  File "D:\git\auto_job__find__chatgpt__rpa\auto_job_find\.venv\lib\site-packages\langchain_community\document_loaders\pebblo.py", line 5, in <module>
    import pwd
ModuleNotFoundError: No module named 'pwd'
```

**Comment by digger-yu** [comment]
https://github.com/langchain-ai/langchain/issues/17514  可以参考这个

```
langchain==0.1.6
langchain-community==0.0.19
langchain-core==0.1.23
```

**Comment by Frrrrrrrrank** [comment]
问题解决了吗...我没复现成功....我给你加个ask for help 标签吧

**Comment by Standindust** [comment]
我也是这个问题，然后把langchain的包和代码都删了 直接用另外一个版本 能跑起来 

> 不应该呀，我的就是windows...你试一下不用langchain的版本

**Comment by Hezhexi2002** [comment]
![image](https://github.com/Frrrrrrrrank/auto_job__find__chatgpt__rpa/assets/53631206/6834482b-3e5c-4ff2-a86e-51bb61246edd)
![image](https://github.com/Frrrrrrrrank/auto_job__find__chatgpt__rpa/assets/53631206/8c2929fc-0107-45e3-a02f-ff48d86c6743)
GPT说的是pwd模块在win下不可用，所以我这里用了getpass模块替代，但是重新运行又又新的错误：
![image](https://github.com/Frrrrrrrrank/auto_job__find__chatgpt__rpa/assets/53631206/24967255-31fd-46c3-915e-143766a29b39)
看起来像是代理问题，但是我使用的moonshot的自定义api，单独curl是没问题的：
![image](https://github.com/Frrrrrrrrank/auto_job__find__chatgpt__rpa/assets/53631206/d63e0bab-cee7-4452-8ffd-8110db65ba7e)
![image](https://github.co@Frrrrrrrrank /Frrrrrrrrank/auto_job__find__chatgpt__rpa/assets/53631206/2830a00e-ad05-4b09-b318-e3ab3520e1e8)
@Frrrrrrrrank 希望大佬能看看是怎么回事（

**Comment by 507402** [comment]
> ![image](https://private-user-images.githubusercontent.com/53631206/309290668-6834482b-3e5c-4ff2-a86e-51bb61246edd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyNTg0OTMsIm5iZiI6MTcxMjI1ODE5MywicGF0aCI6Ii81MzYzMTIwNi8zMDkyOTA2NjgtNjgzNDQ4MmItM2U1Yy00ZmYyLWE4NmUtNTFiYjYxMjQ2ZWRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDE5MTYzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhMTA2ZTQ1MmM2YzljMjNkOTg0N2NiYTg3MjQ2ZjFhMzliYTNhM2VhMWJkNDY3M2VkMzU5ZWM4MGIxMTQwNzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EvidBwqcEFYsWCntA8I7IvtDutEpXqBH0z8StNK59Eg) ![image](https://private-user-images.githubusercontent.com/53631206/309290781-8c2929fc-0107-45e3-a02f-ff48d86c6743.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyNTg0OTMsIm5iZiI6MTcxMjI1ODE5MywicGF0aCI6Ii81MzYzMTIwNi8zMDkyOTA3ODEtOGMyOTI5ZmMtMDEwNy00NWUzLWEwMmYtZmY0OGQ4NmM2NzQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDE5MTYzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExOGM2MWQ0YjU5ZDlkYWNiMWY2YTBmMTMxMTE5ZWRlNWQ1MzYyZTJlNTFmM2Y0YmU4MTk1ZTRmNmI2ZTBhODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xwF9ijSKVqfTPphXqqX8DCqATitu1iPbIk92ISQwgTw)GPT说的是pwd模块在win下不可用，所以我这里用了getpass模块替代，但是重新运行又新的错误： ![image](https://private-user-images.githubusercontent.com/53631206/309291103-24967255-31fd-46c3-915e-143766a29b39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyNTg0OTMsIm5iZiI6MTcxMjI1ODE5MywicGF0aCI6Ii81MzYzMTIwNi8zMDkyOTExMDMtMjQ5NjcyNTUtMzFmZC00NmMzLTkxNWUtMTQzNzY2YTI5YjM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDE5MTYzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxMjRkOTZmNjc1MDU0ZWQ2ZGI4ZDhjZDFhYmVmYTUxNTkyNzJkYTEwYzcyNDA3MDgyZTAyNjlkNmYxZjY1OWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nZyZwfho5pfSqaJCtBd-1p_GopwaE9WiY6aQYP3RyAo) 看起来像是代理问题，但是我使用的大胆创新计划的自定义API，单独curl是没问题的： ![image](https://private-user-images.githubusercontent.com/53631206/309291315-d63e0bab-cee7-4452-8ffd-8110db65ba7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyNTg0OTMsIm5iZiI6MTcxMjI1ODE5MywicGF0aCI6Ii81MzYzMTIwNi8zMDkyOTEzMTUtZDYzZTBiYWItY2VlNy00NDUyLThmZmQtODExMGRiNjViYTdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDE5MTYzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzMzI5NWY4ZGZmY2QxMGZiMWRjNTUxZDk3MGUyNTJmZThhOGFkMDY2NjFlZTI5YmMwYTNjNDI2NGVkNjg0NjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hoRDPiQi1K9PQFgVaBNUcMglnMGZdECW54C5p9rY_30) ![image](https://private-user-images.githubusercontent.com/53631206/309291669-c22d6d78-e274-421a-9468-048591a1c0bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyNTg0OTMsIm5iZiI6MTcxMjI1ODE5MywicGF0aCI6Ii81MzYzMTIwNi8zMDkyOTE2NjktYzIyZDZkNzgtZTI3NC00MjFhLTk0NjgtMDQ4NTkxYTFjMGJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDE5MTYzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiYTkxMzc4MTNlZWRjZmI2NDI3MWE5MGI5NzY4NzhmZTE0ZTYxNjY1YWRhOGExYTFmODk4NTg4NWQxZDNkOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.o9g72nDzT8Nmzss7BW3r97cJzmqTNkETPLYeEilr960) 希望大佬能看看是怎么回事（

我觉得你的connection error可能就是代理的问题，没有挂代理就会出现这个报错，或者代理挂的有问题；pwd的错误可以试试在pycharm将python环境更改为本机的环境

**Comment by loks666** [comment]
> > ![image](https://private-user-images.githubusercontent.com/53631206/309290668-6834482b-3e5c-4ff2-a86e-51bb61246edd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyNTg0OTMsIm5iZiI6MTcxMjI1ODE5MywicGF0aCI6Ii81MzYzMTIwNi8zMDkyOTA2NjgtNjgzNDQ4MmItM2U1Yy00ZmYyLWE4NmUtNTFiYjYxMjQ2ZWRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDE5MTYzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhMTA2ZTQ1MmM2YzljMjNkOTg0N2NiYTg3MjQ2ZjFhMzliYTNhM2VhMWJkNDY3M2VkMzU5ZWM4MGIxMTQwNzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EvidBwqcEFYsWCntA8I7IvtDutEpXqBH0z8StNK59Eg) ![image](https://private-user-images.githubusercontent.com/53631206/309290781-8c2929fc-0107-45e3-a02f-ff48d86c6743.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyNTg0OTMsIm5iZiI6MTcxMjI1ODE5MywicGF0aCI6Ii81MzYzMTIwNi8zMDkyOTA3ODEtOGMyOTI5ZmMtMDEwNy00NWUzLWEwMmYtZmY0OGQ4NmM2NzQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDE5MTYzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExOGM2MWQ0YjU5ZDlkYWNiMWY2YTBmMTMxMTE5ZWRlNWQ1MzYyZTJlNTFmM2Y0YmU4MTk1ZTRmNmI2ZTBhODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xwF9ijSKVqfTPphXqqX8DCqATitu1iPbIk92ISQwgTw)GPT说的是pwd模块在win下不可用，所以我这里用了getpass模块替代，但是重新运行又新的错误： ![image](https://private-user-images.githubusercontent.com/53631206/309291103-24967255-31fd-46c3-915e-143766a29b39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyNTg0OTMsIm5iZiI6MTcxMjI1ODE5MywicGF0aCI6Ii81MzYzMTIwNi8zMDkyOTExMDMtMjQ5NjcyNTUtMzFmZC00NmMzLTkxNWUtMTQzNzY2YTI5YjM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDE5MTYzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxMjRkOTZmNjc1MDU0ZWQ2ZGI4ZDhjZDFhYmVmYTUxNTkyNzJkYTEwYzcyNDA3MDgyZTAyNjlkNmYxZjY1OWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nZyZwfho5pfSqaJCtBd-1p_GopwaE9WiY6aQYP3RyAo) 看起来像是代理问题，但是我使用的大胆创新计划的自定义API，单独curl是没问题的： ![image](https://private-user-images.githubusercontent.com/53631206/309291315-d63e0bab-cee7-4452-8ffd-8110db65ba7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyNTg0OTMsIm5iZiI6MTcxMjI1ODE5MywicGF0aCI6Ii81MzYzMTIwNi8zMDkyOTEzMTUtZDYzZTBiYWItY2VlNy00NDUyLThmZmQtODExMGRiNjViYTdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDE5MTYzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzMzI5NWY4ZGZmY2QxMGZiMWRjNTUxZDk3MGUyNTJmZThhOGFkMDY2NjFlZTI5YmMwYTNjNDI2NGVkNjg0NjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hoRDPiQi1K9PQFgVaBNUcMglnMGZdECW54C5p9rY_30) ![image](https://private-user-images.githubusercontent.com/53631206/309291669-c22d6d78-e274-421a-9468-048591a1c0bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyNTg0OTMsIm5iZiI6MTcxMjI1ODE5MywicGF0aCI6Ii81MzYzMTIwNi8zMDkyOTE2NjktYzIyZDZkNzgtZTI3NC00MjFhLTk0NjgtMDQ4NTkxYTFjMGJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDE5MTYzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiYTkxMzc4MTNlZWRjZmI2NDI3MWE5MGI5NzY4NzhmZTE0ZTYxNjY1YWRhOGExYTFmODk4NTg4NWQxZDNkOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.o9g72nDzT8Nmzss7BW3r97cJzmqTNkETPLYeEilr960) 希望大佬能看看是怎么回事（
> 
> 我觉得你的connection error可能就是代理的问题，没有挂代理就会出现这个报错，或者代理挂的有问题；pwd的错误可以试试在pycharm将python环境更改为本机的环境

这问题可以关了，我参照作者的写了一个基于Java的，欢迎使用提出宝贵意见：https://github.com/loks666/get_jobs

**Comment by loks666** [comment]
项目运行的时候坑有点多，我参照作者的写了一个基于Java的（支持boss，拉勾，猎聘，智联和51job），欢迎使用提出宝贵意见：https://github.com/loks666/get_jobs
