### ISSUE TITLE
希望能提供自定义API接口的功能

### ISSUE THREAD

**Issue by SDLi416** [Frrrrrrrrank/auto_job__find__chatgpt__rpa#5]
如题，国内使用openai挺不方便的，大部分情况下还是需要转发

**Comment by Frrrrrrrrank** [comment]
类似文心一言是吧？我之前看他们的文档，似乎没有类似chatgpt的assistant的功能，这个是openai去年十一月那会发布的，我是创建了assistant来做简历的检索。如果文心一言api没这个功能，那是不是得用langchain一类的外部库，我之前用langchain和llama2-7B做过chat with pdf，感觉有点吃性能，配置环境也有点麻烦。要是有别的实现方式可以在这里介绍一下

如果哪位朋友愿意做这个接口的话，可以跟我说一下，我给你个协作者然后拉个分支

**Comment by SDLi416** [comment]
> 类似文心一言是吧？我之前看他们的文档，似乎没有类似chatgpt的assistant的功能，这个是openai去年十一月那会发布的，我是创建了assistant来做简历的检索。如果文心一言api没这个功能，那是不是得用langchain一类的外部库，我之前用langchain和llama2-7B做过chat with pdf，感觉有点吃性能，配置环境也有点麻烦。要是有别的实现方式可以在这里介绍一下
> 
> 如果哪位朋友愿意做这个接口的话，可以跟我说一下，我给你个协作者然后拉个分支

其实我一开始的需求是想要更改openai包请求的接口，然后我发现通过设置OPENAI_BASE_URL环境变量就可以解决了
国内有一些提供了和openai官方api参数一致的api，但是我试了下并不支持使用assistant。。
如果想要不使用assistant的话可能用langchain一类的确实会方便一些，环境配置倒是还好

说到环境配置，是不是导出一个requirement.txt之类的会好一些呢。。我一开始跑起来的时候还得一个个模块去安装来着😂

**Comment by Frrrrrrrrank** [comment]
> > 类似文心一言是吧？我之前看他们的文档，似乎没有类似chatgpt的assistant的功能，这个是openai去年十一月那会发布的，我是创建了assistant来做简历的检索。如果文心一言api没这个功能，那是不是得用langchain一类的外部库，我之前用langchain和llama2-7B做过chat with pdf，感觉有点吃性能，配置环境也有点麻烦。要是有别的实现方式可以在这里介绍一下
> > 如果哪位朋友愿意做这个接口的话，可以跟我说一下，我给你个协作者然后拉个分支
> 
> 其实我一开始的需求是想要更改openai包请求的接口，然后我发现通过设置OPENAI_BASE_URL环境变量就可以解决了 国内有一些提供了和openai官方api参数一致的api，但是我试了下并不支持使用assistant。。 如果想要不使用assistant的话可能用langchain一类的确实会方便一些，环境配置倒是还好，配置麻烦的应该主要是在llama上？
> 
> 说到环境配置，是不是导出一个requirement.txt之类的会好一些呢。。我一开始跑起来的时候还得一个个模块去安装来着😂
> 
> 另外，这个接口我可以尝试着做一下？刚好最近在试着用langchain做类似的东西，这个也可以练练手

啊哈，我懂了，调用代理api是吧，这个assistant确实不好弄，langchain的话你可以尝试一下，然后可不可以到时候跟我说一下创建个分支，给大伙儿做个贡献，我把我之前做的基于langchain的llama2项目的colab链接发你，你可以直接在那里面看到各个版本的包，我估计把model部分换一下就行，然后改一下pipeline。你点链接以后申请一下，我给你个查看者权限

https://colab.research.google.com/drive/1RNKxCdap6yCgisc6yjOfpc8V9vSd4sTA?usp=sharing

**Comment by SDLi416** [comment]
> https://colab.research.google.com/drive/1RNKxCdap6yCgisc6yjOfpc8V9vSd4sTA?usp=sharing

谢谢，我已经发起请求了哈。分支我后面提交了跟你说，我现在尝试一下

**Comment by SDLi416** [comment]
> > > 类似文心一言是吧？我之前看他们的文档，似乎没有类似chatgpt的assistant的功能，这个是openai去年十一月那会发布的，我是创建了assistant来做简历的检索。如果文心一言api没这个功能，那是不是得用langchain一类的外部库，我之前用langchain和llama2-7B做过chat with pdf，感觉有点吃性能，配置环境也有点麻烦。要是有别的实现方式可以在这里介绍一下
> > > 如果哪位朋友愿意做这个接口的话，可以跟我说一下，我给你个协作者然后拉个分支
> > 
> > 
> > 其实我一开始的需求是想要更改openai包请求的接口，然后我发现通过设置OPENAI_BASE_URL环境变量就可以解决了 国内有一些提供了和openai官方api参数一致的api，但是我试了下并不支持使用assistant。。 如果想要不使用assistant的话可能用langchain一类的确实会方便一些，环境配置倒是还好，配置麻烦的应该主要是在llama上？
> > 说到环境配置，是不是导出一个requirement.txt之类的会好一些呢。。我一开始跑起来的时候还得一个个模块去安装来着😂
> > 另外，这个接口我可以尝试着做一下？刚好最近在试着用langchain做类似的东西，这个也可以练练手
> 
> 啊哈，我懂了，调用代理api是吧，这个assistant确实不好弄，langchain的话你可以尝试一下，然后可不可以到时候跟我说一下创建个分支，给大伙儿做个贡献，我把我之前做的基于langchain的llama2项目的colab链接发你，你可以直接在那里面看到各个版本的包，我估计把model部分换一下就行，然后改一下pipeline。你点链接以后申请一下，我给你个查看者权限
> 
> https://colab.research.google.com/drive/1RNKxCdap6yCgisc6yjOfpc8V9vSd4sTA?usp=sharing

我在分支上已经完成了langchain形式来写求职信的功能，测试了下是可以使用第三方api了，也修复了一个推荐页面下会导致崩溃的bug(应该是跟这个问题一致 https://github.com/Frrrrrrrrank/auto_job__find__chatgpt__rpa/issues/1)

方便的话能增加一个协作者权限吗？我提一个PR然后你review一下？
